# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx2G

# Base properties
    minecraft_version = 1.20.1
    forge_version   = 47.4.10
    mapping_channel = parchment
    mapping_version = 2023.09.03

# Mod Properties
    mod_version        = 1.0.0
    maven_group        = com.opticalfeatures
    archives_base_name = opticalfeatures
    mod_id             = opticalfeatures
    mod_name           = StarT Optical Features
    mod_url            = https//nolink.com
    mod_author         = Argxment
    mod_license        = Lesser General Public License v3.0 [LGPLv3.0]

# Dependencies
    gtceu_version         = 1.7.0b
    ldlib_version         = 1.0.40.b
    registrate_version    = MC1.20-1.3.11
    jade_version          = 11.13.2
